export const stockData = [
    { "name": "3M", "ticker": "MMM" },
    { "name": "A. O. Smith", "ticker": "AOS" },
    { "name": "Abbott Laboratories", "ticker": "ABT" },
    { "name": "AbbVie", "ticker": "ABBV" },
    { "name": "Abiomed", "ticker": "ABMD" },
    { "name": "Accenture", "ticker": "ACN" },
    { "name": "Activision Blizzard", "ticker": "ATVI" },
    { "name": "ADM", "ticker": "ADM" },
    { "name": "Adobe", "ticker": "ADBE" },
    { "name": "Advance Auto Parts", "ticker": "AAP" },
    { "name": "Advanced Micro Devices", "ticker": "AMD" },
    { "name": "AES Corp", "ticker": "AES" },
    { "name": "Aflac", "ticker": "AFL" },
    { "name": "Agilent Technologies", "ticker": "A" },
    { "name": "Air Products & Chemicals", "ticker": "APD" },
    { "name": "Akamai Technologies", "ticker": "AKAM" },
    { "name": "Alaska Air Group", "ticker": "ALK" },
    { "name": "Albemarle Corporation", "ticker": "ALB" },
    { "name": "Alexandria Real Estate Equities", "ticker": "ARE" },
    { "name": "Align Technology", "ticker": "ALGN" },
    { "name": "Allegion", "ticker": "ALLE" },
    { "name": "Alliant Energy", "ticker": "LNT" },
    { "name": "Allstate Corp", "ticker": "ALL" },
    { "name": "Alphabet (Class A)", "ticker": "GOOGL" },
    { "name": "Alphabet (Class C)", "ticker": "GOOG" },
    { "name": "Altria Group", "ticker": "MO" },
    { "name": "Amazon", "ticker": "AMZN" },
    { "name": "Amcor", "ticker": "AMCR" },
    { "name": "Ameren Corp", "ticker": "AEE" },
    { "name": "American Airlines Group", "ticker": "AAL" },
    { "name": "American Electric Power", "ticker": "AEP" },
    { "name": "American Express", "ticker": "AXP" },
    { "name": "American International Group", "ticker": "AIG" },
    { "name": "American Tower", "ticker": "AMT" },
    { "name": "American Water Works", "ticker": "AWK" },
    { "name": "Ameriprise Financial", "ticker": "AMP" },
    { "name": "AmerisourceBergen", "ticker": "ABC" },
    { "name": "Ametek", "ticker": "AME" },
    { "name": "Amgen", "ticker": "AMGN" },
    { "name": "Amphenol", "ticker": "APH" },
    { "name": "Analog Devices", "ticker": "ADI" },
    { "name": "Ansys", "ticker": "ANSS" },
    { "name": "Anthem", "ticker": "ANTM" },
    { "name": "Aon", "ticker": "AON" },
    { "name": "APA Corporation", "ticker": "APA" },
    { "name": "Apple", "ticker": "AAPL" },
    { "name": "Applied Materials", "ticker": "AMAT" },
    { "name": "Aptiv", "ticker": "APTV" },
    { "name": "Arista Networks", "ticker": "ANET" },
    { "name": "Arthur J. Gallagher & Co.", "ticker": "AJG" },
    { "name": "Assurant", "ticker": "AIZ" },
    { "name": "AT&T", "ticker": "T" },
    { "name": "Atmos Energy", "ticker": "ATO" },
    { "name": "Autodesk", "ticker": "ADSK" },
    { "name": "Automatic Data Processing", "ticker": "ADP" },
    { "name": "AutoZone", "ticker": "AZO" },
    { "name": "AvalonBay Communities", "ticker": "AVB" },
    { "name": "Avery Dennison", "ticker": "AVY" },
    { "name": "Baker Hughes", "ticker": "BKR" },
    { "name": "Ball Corp", "ticker": "BLL" },
    { "name": "Bank of America", "ticker": "BAC" },
    { "name": "Bath & Body Works Inc.", "ticker": "BBWI" },
    { "name": "Baxter International", "ticker": "BAX" },
    { "name": "Becton Dickinson", "ticker": "BDX" },
    { "name": "Berkshire Hathaway", "ticker": "BRK.B" },
    { "name": "Best Buy", "ticker": "BBY" },
    { "name": "Bio-Rad Laboratories", "ticker": "BIO" },
    { "name": "Bio-Techne", "ticker": "TECH" },
    { "name": "Biogen", "ticker": "BIIB" },
    { "name": "BlackRock", "ticker": "BLK" },
    { "name": "BNY Mellon", "ticker": "BK" },
    { "name": "Boeing", "ticker": "BA" },
    { "name": "Booking Holdings", "ticker": "BKNG" },
    { "name": "BorgWarner", "ticker": "BWA" },
    { "name": "Boston Properties", "ticker": "BXP" },
    { "name": "Boston Scientific", "ticker": "BSX" },
    { "name": "Bristol Myers Squibb", "ticker": "BMY" },
    { "name": "Broadcom", "ticker": "AVGO" },
    { "name": "Broadridge Financial Solutions", "ticker": "BR" },
    { "name": "Brown & Brown", "ticker": "BRO" },
    { "name": "Brown\u2013Forman", "ticker": "BF.B" },
    { "name": "C. H. Robinson", "ticker": "CHRW" },
    { "name": "Cadence Design Systems", "ticker": "CDNS" },
    { "name": "Caesars Entertainment", "ticker": "CZR" },
    { "name": "Campbell Soup", "ticker": "CPB" },
    { "name": "Capital One Financial", "ticker": "COF" },
    { "name": "Cardinal Health", "ticker": "CAH" },
    { "name": "CarMax", "ticker": "KMX" },
    { "name": "Carnival Corporation", "ticker": "CCL" },
    { "name": "Carrier Global", "ticker": "CARR" },
    { "name": "Catalent", "ticker": "CTLT" },
    { "name": "Caterpillar", "ticker": "CAT" },
    { "name": "Cboe Global Markets", "ticker": "CBOE" },
    { "name": "CBRE", "ticker": "CBRE" },
    { "name": "CDW", "ticker": "CDW" },
    { "name": "Celanese", "ticker": "CE" },
    { "name": "Centene Corporation", "ticker": "CNC" },
    { "name": "CenterPoint Energy", "ticker": "CNP" },
    { "name": "Ceridian", "ticker": "CDAY" },
    { "name": "Cerner", "ticker": "CERN" },
    { "name": "CF Industries", "ticker": "CF" },
    { "name": "Charles River Laboratories", "ticker": "CRL" },
    { "name": "Charles Schwab Corporation", "ticker": "SCHW" },
    { "name": "Charter Communications", "ticker": "CHTR" },
    { "name": "Chevron Corporation", "ticker": "CVX" },
    { "name": "Chipotle Mexican Grill", "ticker": "CMG" },
    { "name": "Chubb", "ticker": "CB" },
    { "name": "Church & Dwight", "ticker": "CHD" },
    { "name": "Cigna", "ticker": "CI" },
    { "name": "Cincinnati Financial", "ticker": "CINF" },
    { "name": "Cintas Corporation", "ticker": "CTAS" },
    { "name": "Cisco Systems", "ticker": "CSCO" },
    { "name": "Citigroup", "ticker": "C" },
    { "name": "Citizens Financial Group", "ticker": "CFG" },
    { "name": "Citrix Systems", "ticker": "CTXS" },
    { "name": "Clorox", "ticker": "CLX" },
    { "name": "CME Group", "ticker": "CME" },
    { "name": "CMS Energy", "ticker": "CMS" },
    { "name": "Coca-Cola Company", "ticker": "KO" },
    { "name": "Cognizant Technology Solutions", "ticker": "CTSH" },
    { "name": "Colgate-Palmolive", "ticker": "CL" },
    { "name": "Comcast", "ticker": "CMCSA" },
    { "name": "Comerica", "ticker": "CMA" },
    { "name": "Conagra Brands", "ticker": "CAG" },
    { "name": "ConocoPhillips", "ticker": "COP" },
    { "name": "Consolidated Edison", "ticker": "ED" },
    { "name": "Constellation Brands", "ticker": "STZ" },
    { "name": "Copart", "ticker": "CPRT" },
    { "name": "Corning", "ticker": "GLW" },
    { "name": "Corteva", "ticker": "CTVA" },
    { "name": "Costco", "ticker": "COST" },
    { "name": "Coterra", "ticker": "CTRA" },
    { "name": "Crown Castle", "ticker": "CCI" },
    { "name": "CSX", "ticker": "CSX" },
    { "name": "Cummins", "ticker": "CMI" },
    { "name": "CVS Health", "ticker": "CVS" },
    { "name": "D. R. Horton", "ticker": "DHI" },
    { "name": "Danaher Corporation", "ticker": "DHR" },
    { "name": "Darden Restaurants", "ticker": "DRI" },
    { "name": "DaVita", "ticker": "DVA" },
    { "name": "Deere & Co.", "ticker": "DE" },
    { "name": "Delta Air Lines", "ticker": "DAL" },
    { "name": "Dentsply Sirona", "ticker": "XRAY" },
    { "name": "Devon Energy", "ticker": "DVN" },
    { "name": "DexCom", "ticker": "DXCM" },
    { "name": "Diamondback Energy", "ticker": "FANG" },
    { "name": "Digital Realty Trust", "ticker": "DLR" },
    { "name": "Discover Financial Services", "ticker": "DFS" },
    { "name": "Discovery (Series A)", "ticker": "DISCA" },
    { "name": "Discovery (Series C)", "ticker": "DISCK" },
    { "name": "Dish Network", "ticker": "DISH" },
    { "name": "Dollar General", "ticker": "DG" },
    { "name": "Dollar Tree", "ticker": "DLTR" },
    { "name": "Dominion Energy", "ticker": "D" },
    { "name": "Domino's Pizza", "ticker": "DPZ" },
    { "name": "Dover Corporation", "ticker": "DOV" },
    { "name": "Dow", "ticker": "DOW" },
    { "name": "DTE Energy", "ticker": "DTE" },
    { "name": "Duke Energy", "ticker": "DUK" },
    { "name": "Duke Realty Corp", "ticker": "DRE" },
    { "name": "DuPont", "ticker": "DD" },
    { "name": "DXC Technology", "ticker": "DXC" },
    { "name": "Eastman Chemical", "ticker": "EMN" },
    { "name": "Eaton Corporation", "ticker": "ETN" },
    { "name": "eBay", "ticker": "EBAY" },
    { "name": "Ecolab", "ticker": "ECL" },
    { "name": "Edison International", "ticker": "EIX" },
    { "name": "Edwards Lifesciences", "ticker": "EW" },
    { "name": "Electronic Arts", "ticker": "EA" },
    { "name": "Eli Lilly & Co", "ticker": "LLY" },
    { "name": "Emerson Electric Company", "ticker": "EMR" },
    { "name": "Enphase Energy", "ticker": "ENPH" },
    { "name": "Entergy", "ticker": "ETR" },
    { "name": "EOG Resources", "ticker": "EOG" },
    { "name": "Equifax", "ticker": "EFX" },
    { "name": "Equinix", "ticker": "EQIX" },
    { "name": "Equity Residential", "ticker": "EQR" },
    { "name": "Essex Property Trust", "ticker": "ESS" },
    { "name": "Est\u00e9e Lauder Companies", "ticker": "EL" },
    { "name": "Etsy", "ticker": "ETSY" },
    { "name": "Everest Re", "ticker": "RE" },
    { "name": "Evergy", "ticker": "EVRG" },
    { "name": "Eversource Energy", "ticker": "ES" },
    { "name": "Exelon", "ticker": "EXC" },
    { "name": "Expedia Group", "ticker": "EXPE" },
    { "name": "Expeditors", "ticker": "EXPD" },
    { "name": "Extra Space Storage", "ticker": "EXR" },
    { "name": "ExxonMobil", "ticker": "XOM" },
    { "name": "F5 Networks", "ticker": "FFIV" },
    { "name": "Facebook", "ticker": "FB" },
    { "name": "Fastenal", "ticker": "FAST" },
    { "name": "Federal Realty Investment Trust", "ticker": "FRT" },
    { "name": "FedEx", "ticker": "FDX" },
    { "name": "Fidelity National Information Services", "ticker": "FIS" },
    { "name": "Fifth Third Bancorp", "ticker": "FITB" },
    { "name": "First Republic Bank", "ticker": "FRC" },
    { "name": "FirstEnergy", "ticker": "FE" },
    { "name": "Fiserv", "ticker": "FISV" },
    { "name": "Fleetcor", "ticker": "FLT" },
    { "name": "FMC Corporation", "ticker": "FMC" },
    { "name": "Ford", "ticker": "F" },
    { "name": "Fortinet", "ticker": "FTNT" },
    { "name": "Fortive", "ticker": "FTV" },
    { "name": "Fortune Brands Home & Security", "ticker": "FBHS" },
    { "name": "Fox Corporation (Class A)", "ticker": "FOXA" },
    { "name": "Fox Corporation (Class B)", "ticker": "FOX" },
    { "name": "Franklin Resources", "ticker": "BEN" },
    { "name": "Freeport-McMoRan", "ticker": "FCX" },
    { "name": "Gap", "ticker": "GPS" },
    { "name": "Garmin", "ticker": "GRMN" },
    { "name": "Gartner", "ticker": "IT" },
    { "name": "Generac Holdings", "ticker": "GNRC" },
    { "name": "General Dynamics", "ticker": "GD" },
    { "name": "General Electric", "ticker": "GE" },
    { "name": "General Mills", "ticker": "GIS" },
    { "name": "General Motors", "ticker": "GM" },
    { "name": "Genuine Parts", "ticker": "GPC" },
    { "name": "Gilead Sciences", "ticker": "GILD" },
    { "name": "Global Payments", "ticker": "GPN" },
    { "name": "Globe Life", "ticker": "GL" },
    { "name": "Goldman Sachs", "ticker": "GS" },
    { "name": "Halliburton", "ticker": "HAL" },
    { "name": "Hanesbrands", "ticker": "HBI" },
    { "name": "Hasbro", "ticker": "HAS" },
    { "name": "HCA Healthcare", "ticker": "HCA" },
    { "name": "Healthpeak Properties", "ticker": "PEAK" },
    { "name": "Henry Schein", "ticker": "HSIC" },
    { "name": "Hess Corporation", "ticker": "HES" },
    { "name": "Hewlett Packard Enterprise", "ticker": "HPE" },
    { "name": "Hilton Worldwide", "ticker": "HLT" },
    { "name": "Hologic", "ticker": "HOLX" },
    { "name": "Home Depot", "ticker": "HD" },
    { "name": "Honeywell", "ticker": "HON" },
    { "name": "Hormel", "ticker": "HRL" },
    { "name": "Host Hotels & Resorts", "ticker": "HST" },
    { "name": "Howmet Aerospace", "ticker": "HWM" },
    { "name": "HP", "ticker": "HPQ" },
    { "name": "Humana", "ticker": "HUM" },
    { "name": "Huntington Bancshares", "ticker": "HBAN" },
    { "name": "Huntington Ingalls Industries", "ticker": "HII" },
    { "name": "IBM", "ticker": "IBM" },
    { "name": "IDEX Corporation", "ticker": "IEX" },
    { "name": "Idexx Laboratories", "ticker": "IDXX" },
    { "name": "IHS Markit", "ticker": "INFO" },
    { "name": "Illinois Tool Works", "ticker": "ITW" },
    { "name": "Illumina", "ticker": "ILMN" },
    { "name": "Incyte", "ticker": "INCY" },
    { "name": "Ingersoll Rand", "ticker": "IR" },
    { "name": "Intel", "ticker": "INTC" },
    { "name": "Intercontinental Exchange", "ticker": "ICE" },
    { "name": "International Flavors & Fragrances", "ticker": "IFF" },
    { "name": "International Paper", "ticker": "IP" },
    { "name": "Interpublic Group", "ticker": "IPG" },
    { "name": "Intuit", "ticker": "INTU" },
    { "name": "Intuitive Surgical", "ticker": "ISRG" },
    { "name": "Invesco", "ticker": "IVZ" },
    { "name": "IPG Photonics", "ticker": "IPGP" },
    { "name": "IQVIA", "ticker": "IQV" },
    { "name": "Iron Mountain", "ticker": "IRM" },
    { "name": "J. B. Hunt", "ticker": "JBHT" },
    { "name": "Jack Henry & Associates", "ticker": "JKHY" },
    { "name": "Jacobs Engineering Group", "ticker": "J" },
    { "name": "JM Smucker", "ticker": "SJM" },
    { "name": "Johnson & Johnson", "ticker": "JNJ" },
    { "name": "Johnson Controls", "ticker": "JCI" },
    { "name": "JPMorgan Chase", "ticker": "JPM" },
    { "name": "Juniper Networks", "ticker": "JNPR" },
    { "name": "Kansas City Southern", "ticker": "KSU" },
    { "name": "Kellogg's", "ticker": "K" },
    { "name": "KeyCorp", "ticker": "KEY" },
    { "name": "Keysight Technologies", "ticker": "KEYS" },
    { "name": "Kimberly-Clark", "ticker": "KMB" },
    { "name": "Kimco Realty", "ticker": "KIM" },
    { "name": "Kinder Morgan", "ticker": "KMI" },
    { "name": "KLA Corporation", "ticker": "KLAC" },
    { "name": "Kraft Heinz", "ticker": "KHC" },
    { "name": "Kroger", "ticker": "KR" },
    { "name": "L3Harris Technologies", "ticker": "LHX" },
    { "name": "LabCorp", "ticker": "LH" },
    { "name": "Lam Research", "ticker": "LRCX" },
    { "name": "Lamb Weston", "ticker": "LW" },
    { "name": "Las Vegas Sands", "ticker": "LVS" },
    { "name": "Leggett & Platt", "ticker": "LEG" },
    { "name": "Leidos", "ticker": "LDOS" },
    { "name": "Lennar", "ticker": "LEN" },
    { "name": "Lincoln National", "ticker": "LNC" },
    { "name": "Linde", "ticker": "LIN" },
    { "name": "Live Nation Entertainment", "ticker": "LYV" },
    { "name": "LKQ Corporation", "ticker": "LKQ" },
    { "name": "Lockheed Martin", "ticker": "LMT" },
    { "name": "Loews Corporation", "ticker": "L" },
    { "name": "Lowe's", "ticker": "LOW" },
    { "name": "Lumen Technologies", "ticker": "LUMN" },
    { "name": "LyondellBasell", "ticker": "LYB" },
    { "name": "M&T Bank", "ticker": "MTB" },
    { "name": "Marathon Oil", "ticker": "MRO" },
    { "name": "Marathon Petroleum", "ticker": "MPC" },
    { "name": "MarketAxess", "ticker": "MKTX" },
    { "name": "Marriott International", "ticker": "MAR" },
    { "name": "Marsh & McLennan", "ticker": "MMC" },
    { "name": "Martin Marietta Materials", "ticker": "MLM" },
    { "name": "Masco", "ticker": "MAS" },
    { "name": "Mastercard", "ticker": "MA" },
    { "name": "Match Group", "ticker": "MTCH" },
    { "name": "McCormick & Company", "ticker": "MKC" },
    { "name": "McDonald's", "ticker": "MCD" },
    { "name": "McKesson Corporation", "ticker": "MCK" },
    { "name": "Medtronic", "ticker": "MDT" },
    { "name": "Merck & Co.", "ticker": "MRK" },
    { "name": "MetLife", "ticker": "MET" },
    { "name": "Mettler Toledo", "ticker": "MTD" },
    { "name": "MGM Resorts International", "ticker": "MGM" },
    { "name": "Microchip Technology", "ticker": "MCHP" },
    { "name": "Micron Technology", "ticker": "MU" },
    { "name": "Microsoft", "ticker": "MSFT" },
    { "name": "Mid-America Apartments", "ticker": "MAA" },
    { "name": "Moderna", "ticker": "MRNA" },
    { "name": "Mohawk Industries", "ticker": "MHK" },
    { "name": "Molson Coors Beverage Company", "ticker": "TAP" },
    { "name": "Mondelez International", "ticker": "MDLZ" },
    { "name": "Monolithic Power Systems", "ticker": "MPWR" },
    { "name": "Monster Beverage", "ticker": "MNST" },
    { "name": "Moody's Corporation", "ticker": "MCO" },
    { "name": "Morgan Stanley", "ticker": "MS" },
    { "name": "Motorola Solutions", "ticker": "MSI" },
    { "name": "MSCI", "ticker": "MSCI" },
    { "name": "Nasdaq", "ticker": "NDAQ" },
    { "name": "NetApp", "ticker": "NTAP" },
    { "name": "Netflix", "ticker": "NFLX" },
    { "name": "Newell Brands", "ticker": "NWL" },
    { "name": "Newmont", "ticker": "NEM" },
    { "name": "News Corp (Class A)", "ticker": "NWSA" },
    { "name": "News Corp (Class B)", "ticker": "NWS" },
    { "name": "NextEra Energy", "ticker": "NEE" },
    { "name": "Nielsen Holdings", "ticker": "NLSN" },
    { "name": "Nike", "ticker": "NKE" },
    { "name": "NiSource", "ticker": "NI" },
    { "name": "Norfolk Southern", "ticker": "NSC" },
    { "name": "Northern Trust", "ticker": "NTRS" },
    { "name": "Northrop Grumman", "ticker": "NOC" },
    { "name": "NortonLifeLock", "ticker": "NLOK" },
    { "name": "Norwegian Cruise Line Holdings", "ticker": "NCLH" },
    { "name": "NRG Energy", "ticker": "NRG" },
    { "name": "Nucor", "ticker": "NUE" },
    { "name": "Nvidia", "ticker": "NVDA" },
    { "name": "NVR", "ticker": "NVR" },
    { "name": "NXP", "ticker": "NXPI" },
    { "name": "O'Reilly Automotive", "ticker": "ORLY" },
    { "name": "Occidental Petroleum", "ticker": "OXY" },
    { "name": "Old Dominion Freight Line", "ticker": "ODFL" },
    { "name": "Omnicom Group", "ticker": "OMC" },
    { "name": "Oneok", "ticker": "OKE" },
    { "name": "Oracle", "ticker": "ORCL" },
    { "name": "Organon & Co.", "ticker": "OGN" },
    { "name": "Otis Worldwide", "ticker": "OTIS" },
    { "name": "Paccar", "ticker": "PCAR" },
    { "name": "Packaging Corporation of America", "ticker": "PKG" },
    { "name": "Parker-Hannifin", "ticker": "PH" },
    { "name": "Paychex", "ticker": "PAYX" },
    { "name": "Paycom", "ticker": "PAYC" },
    { "name": "PayPal", "ticker": "PYPL" },
    { "name": "Penn National Gaming", "ticker": "PENN" },
    { "name": "Pentair", "ticker": "PNR" },
    { "name": "People's United Financial", "ticker": "PBCT" },
    { "name": "PepsiCo", "ticker": "PEP" },
    { "name": "PerkinElmer", "ticker": "PKI" },
    { "name": "Pfizer", "ticker": "PFE" },
    { "name": "Philip Morris International", "ticker": "PM" },
    { "name": "Phillips 66", "ticker": "PSX" },
    { "name": "Pinnacle West Capital", "ticker": "PNW" },
    { "name": "Pioneer Natural Resources", "ticker": "PXD" },
    { "name": "PNC Financial Services", "ticker": "PNC" },
    { "name": "Pool Corporation", "ticker": "POOL" },
    { "name": "PPG Industries", "ticker": "PPG" },
    { "name": "PPL", "ticker": "PPL" },
    { "name": "Principal Financial Group", "ticker": "PFG" },
    { "name": "Procter & Gamble", "ticker": "PG" },
    { "name": "Progressive Corporation", "ticker": "PGR" },
    { "name": "Prologis", "ticker": "PLD" },
    { "name": "Prudential Financial", "ticker": "PRU" },
    { "name": "PTC", "ticker": "PTC" },
    { "name": "Public Service Enterprise Group", "ticker": "PEG" },
    { "name": "Public Storage", "ticker": "PSA" },
    { "name": "PulteGroup", "ticker": "PHM" },
    { "name": "PVH", "ticker": "PVH" },
    { "name": "Qorvo", "ticker": "QRVO" },
    { "name": "Qualcomm", "ticker": "QCOM" },
    { "name": "Quanta Services", "ticker": "PWR" },
    { "name": "Quest Diagnostics", "ticker": "DGX" },
    { "name": "Ralph Lauren Corporation", "ticker": "RL" },
    { "name": "Raymond James Financial", "ticker": "RJF" },
    { "name": "Raytheon Technologies", "ticker": "RTX" },
    { "name": "Realty Income Corporation", "ticker": "O" },
    { "name": "Regency Centers", "ticker": "REG" },
    { "name": "Regeneron Pharmaceuticals", "ticker": "REGN" },
    { "name": "Regions Financial Corporation", "ticker": "RF" },
    { "name": "Republic Services", "ticker": "RSG" },
    { "name": "ResMed", "ticker": "RMD" },
    { "name": "Robert Half International", "ticker": "RHI" },
    { "name": "Rockwell Automation", "ticker": "ROK" },
    { "name": "Rollins", "ticker": "ROL" },
    { "name": "Roper Technologies", "ticker": "ROP" },
    { "name": "Ross Stores", "ticker": "ROST" },
    { "name": "Royal Caribbean Group", "ticker": "RCL" },
    { "name": "S&P Global", "ticker": "SPGI" },
    { "name": "Salesforce", "ticker": "CRM" },
    { "name": "SBA Communications", "ticker": "SBAC" },
    { "name": "Schlumberger", "ticker": "SLB" },
    { "name": "Seagate Technology", "ticker": "STX" },
    { "name": "Sealed Air", "ticker": "SEE" },
    { "name": "Sempra Energy", "ticker": "SRE" },
    { "name": "ServiceNow", "ticker": "NOW" },
    { "name": "Sherwin-Williams", "ticker": "SHW" },
    { "name": "Simon Property Group", "ticker": "SPG" },
    { "name": "Skyworks Solutions", "ticker": "SWKS" },
    { "name": "Snap-on", "ticker": "SNA" },
    { "name": "Southern Company", "ticker": "SO" },
    { "name": "Southwest Airlines", "ticker": "LUV" },
    { "name": "Stanley Black & Decker", "ticker": "SWK" },
    { "name": "Starbucks", "ticker": "SBUX" },
    { "name": "State Street Corporation", "ticker": "STT" },
    { "name": "Steris", "ticker": "STE" },
    { "name": "Stryker Corporation", "ticker": "SYK" },
    { "name": "SVB Financial", "ticker": "SIVB" },
    { "name": "Synchrony Financial", "ticker": "SYF" },
    { "name": "Synopsys", "ticker": "SNPS" },
    { "name": "Sysco", "ticker": "SYY" },
    { "name": "T-Mobile US", "ticker": "TMUS" },
    { "name": "T. Rowe Price", "ticker": "TROW" },
    { "name": "Take-Two Interactive", "ticker": "TTWO" },
    { "name": "Tapestry", "ticker": "TPR" },
    { "name": "Target Corporation", "ticker": "TGT" },
    { "name": "TE Connectivity", "ticker": "TEL" },
    { "name": "Teledyne Technologies", "ticker": "TDY" },
    { "name": "Teleflex", "ticker": "TFX" },
    { "name": "Teradyne", "ticker": "TER" },
    { "name": "Tesla", "ticker": "TSLA" },
    { "name": "Texas Instruments", "ticker": "TXN" },
    { "name": "Textron", "ticker": "TXT" },
    { "name": "The Cooper Companies", "ticker": "COO" },
    { "name": "The Hartford", "ticker": "HIG" },
    { "name": "The Hershey Company", "ticker": "HSY" },
    { "name": "The Mosaic Company", "ticker": "MOS" },
    { "name": "The Travelers Companies", "ticker": "TRV" },
    { "name": "The Walt Disney Company", "ticker": "DIS" },
    { "name": "Thermo Fisher Scientific", "ticker": "TMO" },
    { "name": "TJX Companies", "ticker": "TJX" },
    { "name": "Tractor Supply Company", "ticker": "TSCO" },
    { "name": "Trane Technologies", "ticker": "TT" },
    { "name": "TransDigm Group", "ticker": "TDG" },
    { "name": "Trimble", "ticker": "TRMB" },
    { "name": "Truist Financial", "ticker": "TFC" },
    { "name": "Twitter", "ticker": "TWTR" },
    { "name": "Tyler Technologies", "ticker": "TYL" },
    { "name": "Tyson Foods", "ticker": "TSN" },
    { "name": "U.S. Bancorp", "ticker": "USB" },
    { "name": "UDR", "ticker": "UDR" },
    { "name": "Ulta Beauty", "ticker": "ULTA" },
    { "name": "Under Armour (Class A)", "ticker": "UAA" },
    { "name": "Under Armour (Class C)", "ticker": "UA" },
    { "name": "Union Pacific", "ticker": "UNP" },
    { "name": "United Airlines", "ticker": "UAL" },
    { "name": "United Parcel Service", "ticker": "UPS" },
    { "name": "United Rentals", "ticker": "URI" },
    { "name": "UnitedHealth Group", "ticker": "UNH" },
    { "name": "Universal Health Services", "ticker": "UHS" },
    { "name": "Valero Energy", "ticker": "VLO" },
    { "name": "Ventas", "ticker": "VTR" },
    { "name": "Verisign", "ticker": "VRSN" },
    { "name": "Verisk Analytics", "ticker": "VRSK" },
    { "name": "Verizon Communications", "ticker": "VZ" },
    { "name": "Vertex Pharmaceuticals", "ticker": "VRTX" },
    { "name": "VF Corporation", "ticker": "VFC" },
    { "name": "ViacomCBS", "ticker": "VIAC" },
    { "name": "Viatris", "ticker": "VTRS" },
    { "name": "Visa", "ticker": "V" },
    { "name": "Vornado Realty Trust", "ticker": "VNO" },
    { "name": "Vulcan Materials", "ticker": "VMC" },
    { "name": "W. R. Berkley Corporation", "ticker": "WRB" },
    { "name": "W. W. Grainger", "ticker": "GWW" },
    { "name": "Wabtec", "ticker": "WAB" },
    { "name": "Walgreens Boots Alliance", "ticker": "WBA" },
    { "name": "Walmart", "ticker": "WMT" },
    { "name": "Waste Management", "ticker": "WM" },
    { "name": "Waters Corporation", "ticker": "WAT" },
    { "name": "WEC Energy Group", "ticker": "WEC" },
    { "name": "Wells Fargo", "ticker": "WFC" },
    { "name": "Welltower", "ticker": "WELL" },
    { "name": "West Pharmaceutical Services", "ticker": "WST" },
    { "name": "Western Digital", "ticker": "WDC" },
    { "name": "Western Union", "ticker": "WU" },
    { "name": "WestRock", "ticker": "WRK" },
    { "name": "Weyerhaeuser", "ticker": "WY" },
    { "name": "Whirlpool Corporation", "ticker": "WHR" },
    { "name": "Williams Companies", "ticker": "WMB" },
    { "name": "Willis Towers Watson", "ticker": "WLTW" },
    { "name": "Wynn Resorts", "ticker": "WYNN" },
    { "name": "Xcel Energy", "ticker": "XEL" },
    { "name": "Xilinx", "ticker": "XLNX" },
    { "name": "Xylem", "ticker": "XYL" },
    { "name": "Yum! Brands", "ticker": "YUM" },
    { "name": "Zebra Technologies", "ticker": "ZBRA" },
    { "name": "Zimmer Biomet", "ticker": "ZBH" },
    { "name": "Zions Bancorp", "ticker": "ZION" },
    { "name": "Zoetis", "ticker": "ZTS" }
]